### ISSUE TITLE
Invalid link path ( /ko/README.md )

### ISSUE THREAD

**Issue by jmy3155** [naver/clova-developer-guide#1]
테이블 내의 링크의 경로가 잘못되었습니다.

**Comment by danjimilk** [comment]
@jmy3155 

확인 감사드립니다. 바로 조치하도록 하겠습니다.

**Comment by danjimilk** [comment]
@jmy3155 

안녕하세요. 조금 오해가 있는 것 같아서 설명을 드릴려고 합니다. 이 저장소는 [NAVER 개발자 센터](http://developers.naver.com/]에 [Clova 개발자 가이드](https://developers.naver.com/docs/clova/guide/) 문서를 배포하기 위해 생성되었습니다. 이 저장소에서의 링크는 유효하지 않으니 참고하시기 바랍니다. :)

**Comment by jmy3155** [comment]
@danjimilk 

제가 이 저장소에 대해 잘못 이해했네요. 감사합니다. 😄

**Comment by danjimilk** [comment]
@jmy3155 
아닙니다. 관심가져 주셔서 정말 감사합니다. 즐거운 하루 되세요~
